AWSTemplateFormatVersion: 2010-09-09

Description: Creates CloudWatch Dashboard and alarms for AWS Outposts

Metadata:
  Authors:
    Description: Diego Perez Holguin (diegoph@amazon.com.ar)
  License:
    Description:
      "Copyright 2023 Amazon.com, Inc. and its affiliates. All Rights Reserved.
      SPDX-License-Identifier: MIT-0"

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: AWS Outposts CloudWactch dashboard and alarms
        Parameters:
          - OutpostsID
          - VirtualInterfaceGroupId
          - VirtualInterface1Id
          - VirtualInterface2Id
          - SNSEmailAddress
    ParameterLabels:
      OutpostsID:
        default: AWS Outposts ID
      VirtualInterfaceGroupId:
        default: Virtual Interface Group ID
      VirtualInterface1Id:
        default: Virtual Interface 1 ID
      VirtualInterface2Id:
        default: Virtual Interface 2 ID
      SNSEmailAddress:
        default: SNS e-mail notification address

Parameters:
  SNSEmailAddress:
    Description: The email address for SNS notifications.
    Default: "diegoph@amazon.com"
    Type: String
  OutpostsID:
    Description: AWS Outposts ID (without "op-" prefix).
    Default: "05d2acf0919c259c2"
    Type: String

  VirtualInterfaceGroupId:
    Description: Virtual Interface Group ID.
    Default: "lgw-vif-grp-0b42fccd11d11456b"
    Type: String

  VirtualInterface1Id:
    Description: Virtual Interface 1 ID.
    Default: "lgw-vif-078ed418118214ad3"
    Type: String

  VirtualInterface2Id:
    Description: Virtual Interface 2 ID.
    Default: "lgw-vif-027c6010768f3be49"
    Type: String

Resources:

  OutpostsDashboard:
    Type: AWS::CloudWatch::Dashboard
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      DashboardName: !Sub 'Outposts-Corporativo-${AWS::StackName}-${AWS::Region}'
      DashboardBody: !Sub
        '{
            "start": "-PT24H",
            "widgets": [
                {
                    "height": 5,
                    "width": 4,
                    "y": 0,
                    "x": 0,
                    "type": "metric",
                    "properties": {
                        "view": "gauge",
                        "title": "ARSAT Outpost Corporative Dashboard metrics",
                        "region": "${AWS::Region}",
                        "metrics": [
                            [ "AWS/Outposts", "ConnectedStatus", "OutpostId", "op-${OutpostsID}", { "region": "${AWS::Region}" } ]
                        ],
                        "yAxis": {
                            "left": {
                                "min": 0,
                                "max": 1
                            }
                        },
                        "period": 300,
                        "annotations": {
                            "horizontal": [
                                {
                                    "color": "#b2df8d",
                                    "label": "Connected",
                                    "value": 0.999,
                                    "fill": "above"
                                },
                                {
                                    "color": "#d62728",
                                    "label": "Disconnected",
                                    "value": 0.999,
                                    "fill": "below"
                                }
                            ]
                        },
                        "setPeriodToTimeRange": true,
                        "stacked": false
                    }
                },
                {
                    "height": 6,
                    "width": 4,
                    "y": 5,
                    "x": 0,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ { "label": "S3OutpostAvailability (%)", "expression": "100*(outpostfreebytes/outposttotalbytes)", "region": "${AWS::Region}" } ],
                            [ "AWS/S3Outposts", "OutpostFreeBytes", "OutpostId", "op-${OutpostsID}", { "label": "outpostfreebytes", "visible": false, "id": "outpostfreebytes", "region": "${AWS::Region}" } ],
                            [ ".", "OutpostTotalBytes", ".", ".", { "label": "outposttotalbytes", "visible": false, "id": "outposttotalbytes", "region": "${AWS::Region}" } ]
                        ],
                        "view": "singleValue",
                        "title": "S3 Outposts Availability (%)",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "yAxis": {
                            "left": {
                                "label": "Percent",
                                "showUnits": false
                            }
                        },
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 6,
                    "width": 4,
                    "y": 5,
                    "x": 12,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "EBSVolumeTypeCapacityAvailability", "OutpostId", "op-${OutpostsID}", "VolumeType", "gp2", { "region": "${AWS::Region}" } ]
                        ],
                        "view": "singleValue",
                        "title": "EBS Availability (%)",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 6,
                    "width": 8,
                    "y": 5,
                    "x": 16,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "EBSVolumeTypeCapacityAvailabilityGB", "OutpostId", "op-${OutpostsID}", "VolumeType", "gp2", { "region": "${AWS::Region}", "color": "#d62728", "visible": false } ],
                            [ ".", "EBSVolumeTypeCapacityUtilizationGB", ".", ".", ".", ".", { "region": "${AWS::Region}", "color": "#2ca02c" } ]
                        ],
                        "view": "timeSeries",
                        "title": "EBS Availability (GB)",
                        "region": "${AWS::Region}",
                        "stacked": false,
                        "period": 300,
                        "stat": "Maximum",
                        "yAxis": {
                            "left": {
                                "min": 0
                            }
                        },
                        "annotations": {
                            "horizontal": [
                                {
                                    "label": "100%",
                                    "value": 56150
                                },
                                {
                                    "label": "50%",
                                    "value": 28075
                                }
                            ]
                        }
                    }
                },
                {
                    "height": 7,
                    "width": 4,
                    "y": 11,
                    "x": 0,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "InstanceTypeCapacityAvailability", "OutpostId", "op-${OutpostsID}", "InstanceType", "m5.large", { "region": "${AWS::Region}" } ],
                            [ ".", "UsedInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ],
                            [ ".", "AvailableInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ]
                        ],
                        "view": "singleValue",
                        "title": "m5.large",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 7,
                    "width": 4,
                    "y": 11,
                    "x": 4,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "InstanceTypeCapacityAvailability", "OutpostId", "op-${OutpostsID}", "InstanceType", "m5.xlarge", { "region": "${AWS::Region}" } ],
                            [ ".", "UsedInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ],
                            [ ".", "AvailableInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ]
                        ],
                        "view": "singleValue",
                        "title": "m5.xlarge",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 7,
                    "width": 4,
                    "y": 11,
                    "x": 8,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "InstanceTypeCapacityAvailability", "OutpostId", "op-${OutpostsID}", "InstanceType", "m5.2xlarge", { "region": "${AWS::Region}" } ],
                            [ ".", "UsedInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ],
                            [ ".", "AvailableInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ]
                        ],
                        "view": "singleValue",
                        "title": "m5.2xlarge",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 7,
                    "width": 4,
                    "y": 11,
                    "x": 12,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "InstanceTypeCapacityAvailability", "OutpostId", "op-${OutpostsID}", "InstanceType", "m5.4xlarge", { "region": "${AWS::Region}" } ],
                            [ ".", "UsedInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ],
                            [ ".", "AvailableInstanceType_Count", ".", ".", ".", ".", { "region": "${AWS::Region}" } ]
                        ],
                        "view": "singleValue",
                        "title": "m5.4xlarge",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 5,
                    "width": 10,
                    "y": 0,
                    "x": 14,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "IfTrafficOut", "VirtualInterfaceId", "${VirtualInterface2Id}", "OutpostsId", "${OutpostsID}", "VirtualInterfaceGroupId", "${VirtualInterfaceGroupId}" ],
                            [ ".", "IfTrafficIn", ".", ".", ".", ".", ".", "." ]
                        ],
                        "view": "timeSeries",
                        "title": "Local Gateway VIF-2 network traffic",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 5,
                    "width": 10,
                    "y": 0,
                    "x": 4,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ "AWS/Outposts", "IfTrafficIn", "VirtualInterfaceId", "${VirtualInterface1Id}", "OutpostsId", "${OutpostsID}", "VirtualInterfaceGroupId", "${VirtualInterfaceGroupId}" ],
                            [ ".", "IfTrafficOut", ".", ".", ".", ".", ".", "." ]
                        ],
                        "view": "timeSeries",
                        "title": "Local Gateway VIF-1 network traffic",
                        "region": "${AWS::Region}",
                        "stacked": true,
                        "period": 300,
                        "stat": "Maximum"
                    }
                },
                {
                    "height": 6,
                    "width": 8,
                    "y": 5,
                    "x": 4,
                    "type": "metric",
                    "properties": {
                        "metrics": [
                            [ { "expression": "(outposttotalbytes - outpostfreebytes)/1000000000", "label": "S3OutpostsUtilization", "id": "e1", "region": "${AWS::Region}" } ],
                            [ "AWS/S3Outposts", "OutpostTotalBytes", "OutpostId", "op-${OutpostsID}", { "label": "outposttotalbytes", "id": "outposttotalbytes", "region": "${AWS::Region}", "visible": false } ],
                            [ ".", "OutpostFreeBytes", ".", ".", { "label": "outpostfreebytes", "id": "outpostfreebytes", "region": "${AWS::Region}", "visible": false } ]
                        ],
                        "view": "timeSeries",
                        "title": "S3 Outposts Utilization (GB)",
                        "region": "${AWS::Region}",
                        "stacked": false,
                        "yAxis": {
                            "left": {
                                "label": "Gigabytes",
                                "showUnits": false,
                                "min": 0
                            }
                        },
                        "period": 300,
                        "stat": "Maximum",
                        "annotations": {
                            "horizontal": [
                                {
                                    "label": "100%",
                                    "value": 52776
                                },
                                {
                                    "label": "50%",
                                    "value": 26388
                                }
                            ]
                        }
                    }
                }
            ]
        }'

  SNSTopic:
    DependsOn: [ OutpostsDashboard ]
    Type: AWS::SNS::Topic
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      DisplayName: !Sub 'Outposts-alarm-notification-${AWS::StackName}'
      TopicName: !Sub 'Outposts-alarm-notification-${AWS::StackName}'

  SNSTopicSubscription:
    Type: AWS::SNS::Subscription
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Endpoint: !Ref SNSEmailAddress
      Protocol: email
      TopicArn: !Ref SNSTopic

  OutpostsEBSCapacityAvailabilityAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: Outposts EBS Volume Capacity lower than 50%
      AlarmDescription: "# Outposts coportativo con capacidad de volumenes de EBS menor al 50%"
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - !Ref SNSTopic
      InsufficientDataActions: []
      MetricName: EBSVolumeTypeCapacityAvailability
      Namespace: AWS/Outposts
      Statistic: Maximum
      Dimensions:
        - Name: OutpostId
          Value: !Sub '${OutpostsID}'
        - Name: VolumeType
          Value: gp2
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 50
      ComparisonOperator: LessThanOrEqualToThreshold
      TreatMissingData: missing

  S3OutpostsCapacityAvailabilityAlarm:
    Type: AWS::CloudWatch::Alarm
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      AlarmName: S3 Outposts Capacity lower than 50%
      AlarmDescription: "# S3 Outposts coportativo con capacidad menor al 50%"
      ActionsEnabled: true
      OKActions: []
      AlarmActions: 
        - !Sub 'arn:aws:sns:${AWS::Region}:646994745391:Outposts-alarm'
      InsufficientDataActions: []
      Dimensions: []
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 50
      ComparisonOperator: LessThanThreshold
      TreatMissingData: missing
      Metrics:
        - Id: e1
          Label: S3OutpostAvailability (%)
          ReturnData: true
          Expression: 100*(m2/m1)
        - Id: m1
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/S3Outposts
              MetricName: OutpostTotalBytes
              Dimensions:
                - Name: OutpostId
                  Value: !Sub '${OutpostsID}'
            Period: 300
            Stat: Maximum
        - Id: m2
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/S3Outposts
              MetricName: OutpostFreeBytes
              Dimensions:
                - Name: OutpostId
                  Value: !Sub '${OutpostsID}'
            Period: 300
            Stat: Maximum
